// Date: 10/14/2013 7:39:05 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package cf.brforgers.mods.DragonScalesEX.client.models;

//import hyghlander.mods.DragonScalesEX.common.entities.EntityModDragon;
import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.util.MathHelper;

public class ModelModDragon extends ModelBase
{
  public static float RightWing1rotateAngleZ;
  public static float LeftWing1rotateAngleZ;
	//fields
    ModelRenderer BackBone;
    ModelRenderer BackBone2;
    ModelRenderer BackBone3;
    ModelRenderer Breast1;
    ModelRenderer Breast2;
    ModelRenderer Breast3;
    ModelRenderer Breast4;
    ModelRenderer Body1;
    ModelRenderer BackBone4;
    ModelRenderer BackBone5;
    ModelRenderer BackBone6;
    ModelRenderer Nostril1;
    ModelRenderer Nostril2;
    ModelRenderer Head1;
    ModelRenderer Cheek;
    ModelRenderer Mouth1;
    ModelRenderer Mouth2;
    ModelRenderer Neck1;
    ModelRenderer Neck2;
    ModelRenderer Neck3;
    ModelRenderer Neck4;
    ModelRenderer Neck5;
    ModelRenderer Neck6;
    ModelRenderer Neck7;
    ModelRenderer Neck8;
    ModelRenderer Neck9;
    ModelRenderer Neck10;
    ModelRenderer Neck11;
    ModelRenderer Neck12;
    ModelRenderer Neck13;
    ModelRenderer Neck14;
    ModelRenderer Body2;
    ModelRenderer Tail1;
    ModelRenderer Tail2;
    ModelRenderer Tail3;
    ModelRenderer Tail4;
    ModelRenderer Tail5;
    ModelRenderer Tail6;
    ModelRenderer Tail7;
    ModelRenderer Tail8;
    ModelRenderer Tail9;
    ModelRenderer Tail10;
    ModelRenderer Tail11;
    ModelRenderer Tail12;
    ModelRenderer Tail13;
    ModelRenderer Tail14;
    ModelRenderer Tail15;
    ModelRenderer Tail16;
    ModelRenderer LeftWing4;
    ModelRenderer LeftWing2;
    ModelRenderer LeftWing3;
    ModelRenderer RightWing1;
    ModelRenderer RightWing2;
    ModelRenderer RightWing3;
    ModelRenderer RightWing4;
    ModelRenderer LeftWing1;
    ModelRenderer rbl1;
    ModelRenderer rbl2;
    ModelRenderer rfl1;
    ModelRenderer rfl2;
    ModelRenderer rfl3;
    ModelRenderer lbl3;
    ModelRenderer lbl2;
    ModelRenderer lbl1;
    ModelRenderer rbl3;
    ModelRenderer lfl1;
    ModelRenderer lfl2;
    ModelRenderer lfl3;
    ModelRenderer RightWingFlap1;
    ModelRenderer RightWingFlap2;
    ModelRenderer RightWingFlap3;
    ModelRenderer RightWingFlap4;
    ModelRenderer LeftWingFlap1;
    ModelRenderer LeftWingFlap2;
    ModelRenderer LeftWingFlap3;
    ModelRenderer LeftWingFlap4;
  
  public ModelModDragon()
  {
    textureWidth = 256;
    textureHeight = 256;
    
    BackBone = new ModelRenderer(this, 100, 0);
    BackBone.addBox(-3F, -1F, 0F, 6, 6, 34);
    BackBone.setRotationPoint(0F, -6F, 24F);
    BackBone.setTextureSize(256, 256);
    BackBone.mirror = true;
    setRotation(BackBone, 0.0113601F, 0F, 0F);
    BackBone2 = new ModelRenderer(this, 100, 0);
    BackBone2.addBox(-2.5F, -2F, 0F, 5, 6, 34);
    BackBone2.setRotationPoint(0F, -6F, 24F);
    BackBone2.setTextureSize(256, 256);
    BackBone2.mirror = true;
    setRotation(BackBone2, 0.0113601F, 0F, 0F);
    BackBone3 = new ModelRenderer(this, 100, 0);
    BackBone3.addBox(-4F, -0.5F, 0F, 8, 5, 34);
    BackBone3.setRotationPoint(0F, -6F, 24F);
    BackBone3.setTextureSize(256, 256);
    BackBone3.mirror = true;
    setRotation(BackBone3, 0.0113601F, 0F, 0F);
    Breast1 = new ModelRenderer(this, 0, 70);
    Breast1.addBox(-5.5F, 0F, 0F, 11, 10, 4);
    Breast1.setRotationPoint(0F, -4F, 0F);
    Breast1.setTextureSize(256, 256);
    Breast1.mirror = true;
    setRotation(Breast1, -0.2488901F, 0F, 0F);
    Breast2 = new ModelRenderer(this, 0, 70);
    Breast2.addBox(-4F, 0F, 0F, 8, 10, 4);
    Breast2.setRotationPoint(0F, -4F, 0F);
    Breast2.setTextureSize(256, 256);
    Breast2.mirror = true;
    setRotation(Breast2, -0.546319F, 0F, 0F);
    Breast3 = new ModelRenderer(this, 0, 70);
    Breast3.addBox(-4.5F, 0F, 0F, 9, 10, 5);
    Breast3.setRotationPoint(0F, -4F, 0F);
    Breast3.setTextureSize(256, 256);
    Breast3.mirror = true;
    setRotation(Breast3, -1.029641F, 0F, 0F);
    Breast4 = new ModelRenderer(this, 0, 70);
    Breast4.addBox(-5F, -1F, -4F, 10, 11, 6);
    Breast4.setRotationPoint(0F, -4F, 0F);
    Breast4.setTextureSize(256, 256);
    Breast4.mirror = true;
    setRotation(Breast4, -1.289891F, 0F, 0F);
    Body1 = new ModelRenderer(this, 100, 0);
    Body1.addBox(-5F, 0F, 0F, 10, 10, 25);
    Body1.setRotationPoint(0F, -4F, 0F);
    Body1.setTextureSize(256, 256);
    Body1.mirror = true;
    setRotation(Body1, 0.0857174F, 0F, 0F);
    BackBone4 = new ModelRenderer(this, 100, 0);
    BackBone4.addBox(-3F, -1F, 0F, 6, 6, 25);
    BackBone4.setRotationPoint(0F, -4F, 0F);
    BackBone4.setTextureSize(256, 256);
    BackBone4.mirror = true;
    setRotation(BackBone4, 0.0857174F, 0F, 0F);
    BackBone5 = new ModelRenderer(this, 100, 0);
    BackBone5.addBox(-2.5F, -2F, 0F, 5, 6, 25);
    BackBone5.setRotationPoint(0F, -4F, 0F);
    BackBone5.setTextureSize(256, 256);
    BackBone5.mirror = true;
    setRotation(BackBone5, 0.0857174F, 0F, 0F);
    BackBone6 = new ModelRenderer(this, 100, 0);
    BackBone6.addBox(-4F, -0.5F, 0F, 8, 5, 25);
    BackBone6.setRotationPoint(0F, -4F, 0F);
    BackBone6.setTextureSize(256, 256);
    BackBone6.mirror = true;
    setRotation(BackBone6, 0.0857174F, 0F, 0F);
    Nostril1 = new ModelRenderer(this, 0, 50);
    Nostril1.addBox(-1.5F, -6F, -0.5F, 1, 2, 2);
    Nostril1.setRotationPoint(0F, -9.5F, 1F);
    Nostril1.setTextureSize(256, 256);
    Nostril1.mirror = true;
    setRotation(Nostril1, 0F, 0F, 0F);
    Nostril2 = new ModelRenderer(this, 7, 50);
    Nostril2.addBox(0.5F, -6F, -0.5F, 1, 2, 2);
    Nostril2.setRotationPoint(0F, -9.5F, 1F);
    Nostril2.setTextureSize(256, 256);
    Nostril2.mirror = true;
    setRotation(Nostril2, 0F, 0F, 0F);
    Head1 = new ModelRenderer(this, 0, 90);
    Head1.addBox(-3F, -9F, -2.5F, 6, 9, 6);
    Head1.setRotationPoint(0F, -2F, -1F);
    Head1.setTextureSize(256, 256);
    Head1.mirror = true;
    setRotation(Head1, 0.25F, 0F, 0F);
    Cheek = new ModelRenderer(this, 0, 59);
    Cheek.addBox(-3.5F, -4F, -2.5F, 7, 4, 4);
    Cheek.setRotationPoint(0F, 0F, 0.1F);
    Cheek.setTextureSize(256, 256);
    Cheek.mirror = true;
    setRotation(Cheek, 0F, 0F, 0F);
    Mouth1 = new ModelRenderer(this, 0, 110);
    Mouth1.addBox(-2.5F, -6F, -0.5F, 5, 9, 2);
    Mouth1.setRotationPoint(0F, -10F, 0F);
    Mouth1.setTextureSize(256, 256);
    Mouth1.mirror = true;
    setRotation(Mouth1, 0F, 0F, 0F);
    Mouth2 = new ModelRenderer(this, 0, 125);
    Mouth2.addBox(-2.5F, -6F, -1.5F, 5, 7, 2);
    Mouth2.setRotationPoint(0F, -10F, -1F);
    Mouth2.setTextureSize(256, 256);
    Mouth2.mirror = true;
    setRotation(Mouth2, 0.528475F, 0F, 0F);
    Neck1 = new ModelRenderer(this, 100, 0);
    Neck1.addBox(-4.5F, -1F, -6F, 9, 10, 2);				//start neck
    Neck1.setRotationPoint(0F, 0F, 0F);
    Neck1.setTextureSize(256, 256);
    Neck1.mirror = true;
    setRotation(Neck1, -0F, 0F, 0F);
    Neck2 = new ModelRenderer(this, 100, 0);
    Neck2.addBox(-4F, 0F, -7F, 8, 8, 2);
    Neck2.setRotationPoint(0F, 1F, 0F);
    Neck2.setTextureSize(256, 256);
    Neck2.mirror = true;
    setRotation(Neck2, -0.2F, 0F, 0F);
    Neck3 = new ModelRenderer(this, 100, 0);
    Neck3.addBox(-3F, -1F, -4F, 6, 6, 4);
    Neck3.setRotationPoint(0F, 1.5F, -5F);
    Neck3.setTextureSize(256, 256);					//
    Neck3.mirror = true;
    setRotation(Neck3, -0.2F, 0F, 0F);
    Neck4 = new ModelRenderer(this, 100, 0);
    Neck4.addBox(-2.5F, -3F, -4F, 5, 6, 4);
    Neck4.setRotationPoint(0F, 2F, -3F);			//
    Neck4.setTextureSize(256, 256);
    Neck4.mirror = true;
    setRotation(Neck4, -0.01F, 0F, 0F);
    Neck5 = new ModelRenderer(this, 100, 0);
    Neck5.addBox(-3F, -3F, -4F, 6, 4, 6);
    Neck5.setRotationPoint(0F, -1F, -5F);
    Neck5.setTextureSize(256, 256);
    Neck5.mirror = true;
    setRotation(Neck5, 1.4F, 0F, 0F);
    Neck6 = new ModelRenderer(this, 100, 0);
    Neck6.addBox(-2.5F, -3F, -4F, 5, 4, 6);
    Neck6.setRotationPoint(0F, -4F, 0F);
    Neck6.setTextureSize(256, 256);
    Neck6.mirror = true;
    setRotation(Neck6, -0.2F, 0F, 0F);
    Neck7 = new ModelRenderer(this, 100, 0);
    Neck7.addBox(-3F, -3F, -4F, 6, 4, 6);
    Neck7.setRotationPoint(0F, -4F, 0F);
    Neck7.setTextureSize(256, 256);
    Neck7.mirror = true;
    setRotation(Neck7, -0.2F, 0F, 0F);
    Neck8 = new ModelRenderer(this, 100, 0);
    Neck8.addBox(-2.5F, -3F, -4F, 5, 4, 6);			//
    Neck8.setRotationPoint(0F, -4F, 0F);
    Neck8.setTextureSize(256, 256);
    Neck8.mirror = true;
    setRotation(Neck8, 0.3F, 0F, 0F);
    Neck9 = new ModelRenderer(this, 100, 0);
    Neck9.addBox(-3F, -3F, -4F, 6, 4, 6);
    Neck9.setRotationPoint(0F, -4F, 0F);
    Neck9.setTextureSize(256, 256);
    Neck9.mirror = true;
    setRotation(Neck9, 0.4F, 0F, 0F);
    Neck10 = new ModelRenderer(this, 100, 0);
    Neck10.addBox(-2.5F, -3F, -4F, 5, 4, 6);
    Neck10.setRotationPoint(0F, -4F, 0F);
    Neck10.setTextureSize(256, 256);
    Neck10.mirror = true;
    setRotation(Neck10, 0.3F, 0F, 0F);
    Neck11 = new ModelRenderer(this, 100, 0);
    Neck11.addBox(-3F, -3F, -4F, 6, 4, 6);
    Neck11.setRotationPoint(0F, -4F, 0F);
    Neck11.setTextureSize(256, 256);
    Neck11.mirror = true;
    setRotation(Neck11, 0.4F, 0F, 0F);
    Neck12 = new ModelRenderer(this, 100, 0);
    Neck12.addBox(-2.5F, -3F, -4F, 5, 4, 6);
    Neck12.setRotationPoint(0F, -4F, 0F);
    Neck12.setTextureSize(256, 256);
    Neck12.mirror = true;
    setRotation(Neck12, 0.1F, 0F, 0F);
    Neck13 = new ModelRenderer(this, 100, 0);
    Neck13.addBox(-3F, -3F, -4F, 6, 4, 6);
    Neck13.setRotationPoint(0F, -4F, 0F);
    Neck13.setTextureSize(256, 256);
    Neck13.mirror = true;
    setRotation(Neck13, 0.5F, 0F, 0F);
    Neck14 = new ModelRenderer(this, 100, 0);
    Neck14.addBox(-2.5F, -3F, -4F, 5, 4, 6);
    Neck14.setRotationPoint(0F, -4F, 0F);
    Neck14.setTextureSize(256, 256);
    Neck14.mirror = true;
    setRotation(Neck14, 0F, 0F, 0F);
    Body2 = new ModelRenderer(this, 100, 0);
    Body2.addBox(-4.5F, 0F, 0F, 9, 10, 34);
    Body2.setRotationPoint(0F, -6F, 24F);
    Body2.setTextureSize(256, 256);
    Body2.mirror = true;
    setRotation(Body2, 0.0113601F, 0F, 0F);
    Tail1 = new ModelRenderer(this, 0, 150);
    Tail1.addBox(-4F, -4F, 0F, 8, 8, 8);
    Tail1.setRotationPoint(0F, 4F, 33F);			////
    Tail1.setTextureSize(256, 256);
    Tail1.mirror = true;
    setRotation(Tail1, 0.1972532F, 0F, 0F);
    Tail2 = new ModelRenderer(this, 0, 150);
    Tail2.addBox(-3.5F, -3.5F, 0F, 7, 7, 8);
    Tail2.setRotationPoint(0F, 0.5F, 7.5F);
    Tail2.setTextureSize(256, 256);
    Tail2.mirror = true;
    setRotation(Tail2, 0.2203249F, 0F, 0F);
    Tail3 = new ModelRenderer(this, 0, 150);
    Tail3.addBox(-3F, -3F, 0F, 6, 6, 8);
    Tail3.setRotationPoint(0F, 0.5F, 7.5F);
    Tail3.setTextureSize(256, 256);
    Tail3.mirror = true;
    setRotation(Tail3, 0.2433965F, 0F, 0F);
    Tail4 = new ModelRenderer(this, 0, 150);
    Tail4.addBox(-2.5F, -2.5F, 0F, 5, 5, 8);
    Tail4.setRotationPoint(0F, 0.5F, 7.5F);
    Tail4.setTextureSize(256, 256);
    Tail4.mirror = true;
    setRotation(Tail4, 0.2036468F, 0F, 0F);
    Tail5 = new ModelRenderer(this, 0, 150);
    Tail5.addBox(-2.5F, -2.5F, 0F, 5, 5, 8);
    Tail5.setRotationPoint(0F, 0.5F, 7.5F);
    Tail5.setTextureSize(256, 256);
    Tail5.mirror = true;
    setRotation(Tail5, 0.263897F, 0F, 0F);
    Tail6 = new ModelRenderer(this, 0, 150);
    Tail6.addBox(-2.5F, -2.5F, 0F, 5, 5, 8);
    Tail6.setRotationPoint(0F, 0.5F, 7.5F);
    Tail6.setTextureSize(256, 256);
    Tail6.mirror = true;
    setRotation(Tail6, 0.224147F, 0F, 0F);
    Tail7 = new ModelRenderer(this, 0, 150);
    Tail7.addBox(-2.5F, -2.5F, 0F, 5, 5, 8);
    Tail7.setRotationPoint(0F, 0.5F, 7.5F);
    Tail7.setTextureSize(256, 256);
    Tail7.mirror = true;
    setRotation(Tail7, 0.247219F, 0F, 0F);
    Tail8 = new ModelRenderer(this, 0, 150);
    Tail8.addBox(-2F, -2F, 0F, 4, 4, 8);
    Tail8.setRotationPoint(0F, 0.F, 7.5F);
    Tail8.setTextureSize(256, 256);							//
    Tail8.mirror = true;
    setRotation(Tail8, 0.2F, 0F, 0F);
    Tail9 = new ModelRenderer(this, 0, 150);
    Tail9.addBox(-2F, -8F, -2F, 4, 8, 4);
    Tail9.setRotationPoint(0F, 0.2F, 7.5F);
    Tail9.setTextureSize(256, 256);
    Tail9.mirror = true;
    setRotation(Tail9, -1.2062179F, 0F, 0F);
    //
    Tail10 = new ModelRenderer(this, 0, 150);			
    Tail10.addBox(-2F, -8F, -2F, 4, 8, 4);
    Tail10.setRotationPoint(0F,-7.5F, -0F);
    Tail10.setTextureSize(256, 256);				//
    Tail10.mirror = true;
    setRotation(Tail10, 0.4664682F, 0F, 0F);
    //
    Tail11 = new ModelRenderer(this, 0, 150);
    Tail11.addBox(-2F, -8F, -2F, 4, 8, 4);
    Tail11.setRotationPoint(0F,-7.5F, -0F);	
    Tail11.setTextureSize(256, 256);			//
    Tail11.mirror = true;
    setRotation(Tail11, 0.538254F, 0F, 0F);
    //
    Tail12 = new ModelRenderer(this, 0, 141);
    Tail12.addBox(-0.5F, -4F, -0.5F, 1, 4, 1);
    Tail12.setRotationPoint(0F, -6F, 0F);
    Tail12.setTextureSize(256, 256);				///
    Tail12.mirror = true;
    setRotation(Tail12, -0.5F, 0F, 0F);
    //
    Tail13 = new ModelRenderer(this, 8, 137);
    Tail13.addBox(-1F, -8F, -1F, 2, 8, 2);
    Tail13.setRotationPoint(0F, -6F, 0F);		///##
    Tail13.setTextureSize(256, 256);
    Tail13.mirror = true;
    setRotation(Tail13, 0.04979F, 0F, 0F);
    //
    Tail14 = new ModelRenderer(this, 0, 141);
    Tail14.addBox(-0.5F, 0F, -0.5F, 1, 4, 1);
    Tail14.setRotationPoint(0F, -6F, 0F);
    Tail14.setTextureSize(256, 256);
    Tail14.mirror = true;							///
    setRotation(Tail14, 0F, 0F, 2.5F);
    //
    Tail15 = new ModelRenderer(this, 0, 141);
    Tail15.addBox(-0.5F, -4F, -0.5F, 1, 4, 1);
    Tail15.setRotationPoint(0F, -6F, 0F);			///
    Tail15.setTextureSize(256, 256);
    Tail15.mirror = true;
    setRotation(Tail15, 0.5F, 0F, 0F);
    //
    Tail16 = new ModelRenderer(this, 0, 141);
    Tail16.addBox(-0.5F, -4F, -0.5F, 1, 4, 1);			///
    Tail16.setRotationPoint(0F, -6F, 0F);
    Tail16.setTextureSize(256, 256);
    Tail16.mirror = true;
    setRotation(Tail16, 0F, 0F, 0.5F);
    //
    LeftWing4 = new ModelRenderer(this, 0, 170);
    LeftWing4.addBox(-1.5F, -31F, -1.5F, 3, 31, 3);
    LeftWing4.setRotationPoint(0F, -30F, 0F);
    LeftWing4.setTextureSize(256, 256);
    LeftWing4.mirror = true;
    setRotation(LeftWing4, -0.6F, 0F, 0F);
    //
    LeftWing2 = new ModelRenderer(this, 0, 170);
    LeftWing2.addBox(-1.5F, -31F, -1.5F, 3, 31, 3);
    LeftWing2.setRotationPoint(1.5F, 0F, 32F);
    LeftWing2.setTextureSize(256, 256);
    LeftWing2.mirror = true;
    setRotation(LeftWing2, 0F, 0F, 0F);
    LeftWing3 = new ModelRenderer(this, 0, 170);
    LeftWing3.addBox(-1.5F, -31F, -1.5F, 3, 31, 3);
    LeftWing3.setRotationPoint(0F, -30F, 0F);
    LeftWing3.setTextureSize(256, 256);
    LeftWing3.mirror = true;
    setRotation(LeftWing3, -2F, 0F, 0F);
    RightWing1 = new ModelRenderer(this, 0, 170);
    RightWing1.addBox(-3F, -3F, 0F, 3, 3, 33);
    RightWing1.setRotationPoint(-5F, -3F, 1F);
    RightWing1.setTextureSize(256, 256);
    RightWing1.mirror = true;
    setRotation(RightWing1, 0.7807508F, 0F, 0F);
    RightWing2 = new ModelRenderer(this, 0, 170);
    RightWing2.addBox(-1.5F, -31F, -1.5F, 3, 31, 3);
    RightWing2.setRotationPoint(-1.5F, 0F, 32F);
    RightWing2.setTextureSize(256, 256);
    RightWing2.mirror = true;
    setRotation(RightWing2, 0F, 0F, 0F);
    RightWing3 = new ModelRenderer(this, 0, 170);
    RightWing3.addBox(-1.5F, -31F, -1.5F, 3, 31, 3);
    RightWing3.setRotationPoint(0F, -30F, 0F);
    RightWing3.setTextureSize(256, 256);
    RightWing3.mirror = true;
    setRotation(RightWing3, -2F, 0F, 0F);
    RightWing4 = new ModelRenderer(this, 0, 170);
    RightWing4.addBox(-1.5F, -31F, -1.5F, 3, 31, 3);
    RightWing4.setRotationPoint(0F, -30F, 0F);
    RightWing4.setTextureSize(256, 256);
    RightWing4.mirror = true;
    setRotation(RightWing4, -0.6F, 0F, 0F);
    LeftWing1 = new ModelRenderer(this, 0, 170);
    LeftWing1.addBox(0F, -3F, 0F, 3, 3, 33);
    LeftWing1.setRotationPoint(5F, -3F, 1F);
    LeftWing1.setTextureSize(256, 256);
    LeftWing1.mirror = true;
    setRotation(LeftWing1, 0.7807508F, 0F, 0F);
    rbl1 = new ModelRenderer(this, 0, 25);
    rbl1.addBox(-1F, -3F, -3F, 5, 12, 8);
    rbl1.setRotationPoint(-8F, 4F, 45F);
    rbl1.setTextureSize(256, 256);
    rbl1.mirror = true;
    setRotation(rbl1, 0.4833219F, 0F, 0F);
    rbl2 = new ModelRenderer(this, 30, 30);
    rbl2.addBox(-1.1F, -3F, -3F, 4, 14, 6);
    rbl2.setRotationPoint(1F, 9F, 1F);
    rbl2.setTextureSize(256, 256);
    rbl2.mirror = true;
    setRotation(rbl2, -0.4602503F, 0F, 0F);
    rbl3 = new ModelRenderer(this, 40, 0);
    rbl3.addBox(-3F, -2F, -13F, 5, 3, 13);
    rbl3.setRotationPoint(1.5F, 10.5F, 4F);
    rbl3.setTextureSize(256, 256);
    rbl3.mirror = true;
    setRotation(rbl3, 0F, 0F, 0F);
    rfl1 = new ModelRenderer(this, 55, 30);
    rfl1.addBox(-1F, -3F, -3F, 5, 12, 6);
    rfl1.setRotationPoint(-8F, 4F, 6F);
    rfl1.setTextureSize(256, 256);
    rfl1.mirror = true;
    setRotation(rfl1, 0.4833219F, 0F, 0F);
    rfl2 = new ModelRenderer(this, 60, 60);
    rfl2.addBox(-1.1F, -3F, -3F, 4, 14, 6);
    rfl2.setRotationPoint(1F, 9F, -1F);
    rfl2.setTextureSize(256, 256);
    rfl2.mirror = true;
    setRotation(rfl2, -0.4602503F, 0F, 0F);
    rfl3 = new ModelRenderer(this, 40, 0);
    rfl3.addBox(-3F, -2F, -13F, 5, 3, 13);
    rfl3.setRotationPoint(1.5F, 10.5F, 4F);
    rfl3.setTextureSize(256, 256);
    rfl3.mirror = true;
    setRotation(rfl3, 0F, 0F, 0F);
    lbl3 = new ModelRenderer(this, 40, 0);
    lbl3.addBox(-3F, -2F, -13F, 5, 3, 13);
    lbl3.setRotationPoint(1.5F, 10.5F, 4F);
    lbl3.setTextureSize(256, 256);
    lbl3.mirror = true;
    setRotation(lbl3, 0F, 0F, 0F);
    lbl2 = new ModelRenderer(this, 30, 30);
    lbl2.addBox(-0.9F, -3F, -3F, 4, 14, 6);
    lbl2.setRotationPoint(0.5F, 9F, 1F);
    lbl2.setTextureSize(256, 256);
    lbl2.mirror = true;
    setRotation(lbl2, -0.4602503F, 0F, 0F);
    lbl1 = new ModelRenderer(this, 0, 25);
    lbl1.addBox(-1F, -3F, -3F, 5, 12, 8);
    lbl1.setRotationPoint(5F, 4F, 45F);
    lbl1.setTextureSize(256, 256);
    lbl1.mirror = true;
    setRotation(lbl1, 0.4833219F, 0F, 0F);
    lfl1 = new ModelRenderer(this, 55, 30);
    lfl1.addBox(-1F, -3F, -3F, 5, 12, 6);
    lfl1.setRotationPoint(5F, 4F, 6F);
    lfl1.setTextureSize(256, 256);
    lfl1.mirror = true;
    setRotation(lfl1, 0.4833219F, 0F, 0F);
    lfl2 = new ModelRenderer(this, 60, 60);
    lfl2.addBox(-0.9F, -3F, -3F, 4, 14, 6);
    lfl2.setRotationPoint(1F, 9F, -1F);
    lfl2.setTextureSize(256, 256);
    lfl2.mirror = true;
    setRotation(lfl2, -0.4602503F, 0F, 0F);
    lfl3 = new ModelRenderer(this, 40, 0);
    lfl3.addBox(-3F, -2F, -13F, 5, 3, 13);
    lfl3.setRotationPoint(1.5F, 10.5F, 4F);
    lfl3.setTextureSize(256, 256);
    lfl3.mirror = true;
    setRotation(lfl3, 0F, 0F, 0F);
    RightWingFlap1 = new ModelRenderer(this, 0, 208);
    RightWingFlap1.addBox(0F, 0F, -14F, 1, 18, 28);
    RightWingFlap1.setRotationPoint(-1F, 0F, 19.5F);
    RightWingFlap1.setTextureSize(256, 256);
    RightWingFlap1.mirror = true;
    setRotation(RightWingFlap1, 0F, 0F, 0F);
    RightWingFlap2 = new ModelRenderer(this, 76, 202);
    RightWingFlap2.addBox(-0.5F, -14F, 0.5F, 1, 27, 27);
    RightWingFlap2.setRotationPoint(0.5F, -13F, 1F);
    RightWingFlap2.setTextureSize(256, 256);
    RightWingFlap2.mirror = true;
    setRotation(RightWingFlap2, 0F, 0F, 0F);
    RightWingFlap3 = new ModelRenderer(this, 134, 202);
    RightWingFlap3.addBox(-0.5F, -14F, 0.5F, 1, 27, 27);
    RightWingFlap3.setRotationPoint(0F, -16F, 0F);
    RightWingFlap3.setTextureSize(256, 256);
    RightWingFlap3.mirror = true;
    setRotation(RightWingFlap3, 0F, 0F, 0F);
    RightWingFlap4 = new ModelRenderer(this, 76, 145);
    RightWingFlap4.addBox(-0.5F, -14F, 0.5F, 1, 27, 27);
    RightWingFlap4.setRotationPoint(0.4F, -15F, 0F);
    RightWingFlap4.setTextureSize(256, 256);
    RightWingFlap4.mirror = true;
    setRotation(RightWingFlap4, 0F, 0F, 0F);
    LeftWingFlap1 = new ModelRenderer(this, 0, 208);
    LeftWingFlap1.addBox(0F, 0F, -14F, 1, 18, 28);
    LeftWingFlap1.setRotationPoint(1F, 0F, 19.5F);
    LeftWingFlap1.setTextureSize(256, 256);
    LeftWingFlap1.mirror = true;
    setRotation(LeftWingFlap1, 0F, 0F, 0F);
    LeftWingFlap2 = new ModelRenderer(this, 76, 202);
    LeftWingFlap2.addBox(-0.5F, -14F, 0.5F, 1, 27, 27);
    LeftWingFlap2.setRotationPoint(0.5F, -13F, 1F);
    LeftWingFlap2.setTextureSize(256, 256);
    LeftWingFlap2.mirror = true;
    setRotation(LeftWingFlap2, 0.0F, 0F, 0F);
    LeftWingFlap3 = new ModelRenderer(this, 134, 202);
    LeftWingFlap3.addBox(-0.5F, -14F, 0.5F, 1, 27, 27);
    LeftWingFlap3.setRotationPoint(0F, -16F, 0F);
    LeftWingFlap3.setTextureSize(256, 256);
    LeftWingFlap3.mirror = true;
    setRotation(LeftWingFlap3, 0F, 0F, 0F);
    LeftWingFlap4 = new ModelRenderer(this, 76, 145);
    LeftWingFlap4.addBox(-0.5F, -14F, 0.5F, 1, 27, 27);
    LeftWingFlap4.setRotationPoint(0.4F, -15F, 0F);
    LeftWingFlap4.setTextureSize(256, 256);
    LeftWingFlap4.mirror = true;
    setRotation(LeftWingFlap4, 0F, 0F, 0F);

      
      //Head
      Head1.addChild(Mouth1);
      Head1.addChild(Mouth2);
      Head1.addChild(Nostril1);
      Head1.addChild(Nostril2);
      Head1.addChild(Cheek);
      
      //Neck
      Breast4.addChild(Neck1);
      Neck1.addChild(Neck2);
      Neck2.addChild(Neck3);
      Neck3.addChild(Neck4);
      Neck4.addChild(Neck5);
      Neck5.addChild(Neck6);
      Neck6.addChild(Neck7);
      Neck7.addChild(Neck8);
      Neck8.addChild(Neck9);
      Neck9.addChild(Neck10);
      Neck10.addChild(Neck11);
      Neck11.addChild(Neck12);
      Neck12.addChild(Neck13);
      Neck13.addChild(Neck14);
      Neck14.addChild(Head1);
      
      //Legs
      //right front
      rfl1.addChild(rfl2);
      rfl2.addChild(rfl3);
      
      //left front
      lfl1.addChild(lfl2);
      lfl2.addChild(lfl3);
      
      //right back
      rbl1.addChild(rbl2);
      rbl2.addChild(rbl3);
      
      //left back
      lbl1.addChild(lbl2);
      lbl2.addChild(lbl3);
      //wings
      LeftWing1.addChild(LeftWing2);
      LeftWing1.addChild(LeftWingFlap1);
      LeftWing2.addChild(LeftWing3);
      LeftWing2.addChild(LeftWingFlap2);
      LeftWing3.addChild(LeftWing4);
      LeftWing3.addChild(LeftWingFlap3);
      LeftWing4.addChild(LeftWingFlap4);
      
      RightWing1.addChild(RightWing2);
      RightWing1.addChild(RightWingFlap1);
      RightWing2.addChild(RightWing3);
      RightWing2.addChild(RightWingFlap2);
      RightWing3.addChild(RightWing4);
      RightWing3.addChild(RightWingFlap3);
      RightWing4.addChild(RightWingFlap4);
      
      //tail
      Body2.addChild(Tail1);
      Tail1.addChild(Tail2);
      Tail2.addChild(Tail3);
      Tail3.addChild(Tail4);
      Tail4.addChild(Tail5);
      Tail5.addChild(Tail6);
      Tail6.addChild(Tail7);
      Tail7.addChild(Tail8);
      Tail8.addChild(Tail9);
      Tail9.addChild(Tail10);
      Tail10.addChild(Tail11);
      Tail13.addChild(Tail12);
      Tail11.addChild(Tail13);
      Tail13.addChild(Tail14);
      Tail13.addChild(Tail15);
      Tail13.addChild(Tail16);
      
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    BackBone.render(f5);
    BackBone2.render(f5);
    BackBone3.render(f5);
    Breast1.render(f5);
    Breast2.render(f5);
    Breast3.render(f5);
    Breast4.render(f5);
    Body1.render(f5);
    BackBone4.render(f5);
    BackBone5.render(f5);
    BackBone6.render(f5);
    Body2.render(f5);
    RightWing1.render(f5);
    LeftWing1.render(f5);
    rbl1.render(f5);
    rfl1.render(f5);
    lbl1.render(f5);
    lfl1.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float par1, float par2, float par3, float par4, float par5, float par6)
  {
	  //Legs
	
	 
	  
	  this.rfl1.rotateAngleX = MathHelper.cos(par1 * 0.6662F + (float)Math.PI) * 1.4F * par2;
	  this.rfl2.rotateAngleX = ((MathHelper.cos(par1 * 0.6662F + (float)Math.PI) * 1.4F * par2)*-1.1F);
	
	  this.lfl1.rotateAngleX = (MathHelper.cos(par1 * 0.6662F) * 1.4F * par2);
	  this.lfl2.rotateAngleX = (MathHelper.cos(par1 * 0.6662F) * 1.4F * par2)*-1.1F;
	  
	  this.rbl1.rotateAngleX = (MathHelper.cos(par1 * 0.6662F) * 1.4F * par2);
	  this.rbl2.rotateAngleX = ((MathHelper.cos(par1 * 0.6662F) * 1.4F * par2)*-1.1F);
	
	  this.lbl1.rotateAngleX = MathHelper.cos(par1 * 0.6662F + (float)Math.PI) * 1.4F * par2;
	  this.lbl2.rotateAngleX = (MathHelper.cos(par1 * 0.6662F + (float)Math.PI) * 1.4F * par2)*-1.1F;
	//Wings
	  
		  //if(EntityModDragon.onGround2 == false){
				//float speedd3 = par2;
	  //this.RightWing1.rotateAngleZ = (((MathHelper.cos(par1 * 0.6662F + (float)Math.PI) * 1.4F * speedd3*-1.1F))*-1/2.5F-0.7F)+((MathHelper.cos(par3/5))/10F)+0.1F;
	  //this.LeftWing1.rotateAngleZ = (((MathHelper.cos(par1 * 0.6662F + (float)Math.PI) * 1.4F * speedd3*-1.1F))/2.5F+0.7F)+((MathHelper.cos(par3/5 + (float)Math.PI))/10F)-0.1F;
			
	  //}
	/**	  //Tail
		  this.Tail1.rotateAngleX = ((MathHelper.sin(par3/10)/2)/10F)+0.2F;
		  this.Tail2.rotateAngleX = ((MathHelper.sin(par3/10)/2)/10F)+0.3F;
		  this.Tail3.rotateAngleX = ((MathHelper.sin(par3/10)/2)/10F)+0.3F;
		  this.Tail4.rotateAngleX = ((MathHelper.sin(par3/10)/2)/10F)+0.2F;
		  this.Tail5.rotateAngleX = ((MathHelper.sin(par3/10)/2)/10F)+0.2F;
		  this.Tail6.rotateAngleX = ((MathHelper.sin(par3/10)/2)/10F)+0.2F;
		  this.Tail7.rotateAngleX = ((MathHelper.sin(par3/10)/2)/10F)+0.2F;
		  this.Tail8.rotateAngleX = ((MathHelper.sin(par3/10)/2)/10F)+0.2F;
		  this.Tail9.rotateAngleX = ((MathHelper.sin(par3/10)/2)/10F)+5F;
		  this.Tail10.rotateAngleX = ((MathHelper.sin(par3/10)/2)/10F)+0.5F;
		  this.Tail11.rotateAngleX = ((MathHelper.sin(par3/10)/2)/10F)+0.5F;
		**/  
		  //Neck
		  this.Neck3.rotateAngleX = ((MathHelper.sin(par3/10+2)/5)/10F)-0.4F;
		  this.Neck4.rotateAngleX = ((MathHelper.sin(par3/10+2)/5)/10F)-0.3F;
		  this.Neck5.rotateAngleX = ((MathHelper.sin(par3/10+2)/5)/10F)+1.8F;
		  this.Neck6.rotateAngleX = ((MathHelper.sin(par3/10+2)/5)/10F)+0.1F;
		  this.Neck7.rotateAngleX = ((MathHelper.sin(par3/10+2)/5)/10F)+0.1F;
		  this.Neck9.rotateAngleX = ((MathHelper.sin(par3/10-1)/5)/10F)+0.2F;
		  this.Neck10.rotateAngleX = ((MathHelper.sin(par3/10+2)/5)/10F)+0.2F;
		  this.Neck11.rotateAngleX = ((MathHelper.sin(par3/10+2)/5)/10F)+0.2F;
		  this.Neck12.rotateAngleX = ((MathHelper.sin(par3/10-2)/5)/10F)+0.2F;
		  this.Neck13.rotateAngleX = ((MathHelper.sin(par3/10-2)/5)/10F)+0.2F;
		  this.Neck14.rotateAngleX = ((MathHelper.sin(par3/10-2)/5)/10F)+0.2F;
	  }
  }
  
